### ISSUE TITLE
model -> Message

### ISSUE THREAD

**Issue by SimoneCerri** [PaoloMarzocchi/bdoctors-back-end#90]
Make a model Message -mcsrR
add also migration and seeder
add relations
Add index page to view messages

**Comment by PaoloMarzocchi** [comment]
add also migration and seeder

**Comment by PaoloMarzocchi** [comment]
add relations

**Comment by marinodilauro** [comment]
Add index page to view messages

**Comment by simone-nolberto** [comment]
Done!
